WebApp3/WhiskyDB.App/Controllers/CaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WhiskyDB.Domain;
using WhiskyDB.Data.Repositories;
using WhiskyDB.App.ViewModels;

namespace WhiskyDB.App.Controllers
{
    public class CaskController : Controller
    {
        private readonly ICaskRepository _caskRepository;
        private readonly IWhiskyRepository _whiskyRepository;

        public CaskController(ICaskRepository caskRepository, IWhiskyRepository whiskyRepository)
        {
            _caskRepository = caskRepository;
            _whiskyRepository = whiskyRepository;
        }

        public IActionResult Index()
        {
            return View(new CaskIndexViewModel() { Casks = _caskRepository.GetAll(), Whiskies = _whiskyRepository.GetAll() });
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Cask cask)
        {
            if (ModelState.IsValid)
            {
                _caskRepository.Add(cask);
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        public IActionResult Delete(int id)
        {
            Cask cask = _caskRepository.GetById(id);
            List<Whisky> whiskies = _whiskyRepository.GetByCask(cask);
            if (whiskies.Count() == 0)
            {
                _caskRepository.Delete(cask);
            }
            else
                return View("CaskDeleteError");
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Cask cask = _caskRepository.GetById(id);
            return View(cask);
        }
        
        [HttpPost]
        public IActionResult Edit(Cask cask)
        {
            if (ModelState.IsValid)
            {
                _caskRepository.Edit(cask.Id, cask.Name, cask.LitreVolume, cask.Predecessor);
                return RedirectToAction("Index");
            }
            else
                return View();
        }
    }
}

WebApp3/WhiskyDB.App/Controllers/DestilleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WhiskyDB.Domain;
using WhiskyDB.Data.Repositories;

namespace WhiskyDB.App.Controllers
{
    public class DestilleryController : Controller
    {
        private readonly IDestilleryRepository _repository;

        public DestilleryController(IDestilleryRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View(_repository.GetAll());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Destillery destillery)
        {
            if (ModelState.IsValid)
            {
                _repository.Add(destillery);
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        public IActionResult Delete(int id)
        {
            Destillery destillery = _repository.GetById(id);
            if (destillery.Whiskys.Count == 0)
            {
                _repository.Delete(destillery);
            }
            else
                return View("DestilleryDeleteError");
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Destillery destillery = _repository.GetById(id);
            return View(destillery);
        }

        [HttpPost]
        public IActionResult Edit(Destillery destillery)
        {
            if (ModelState.IsValid)
            {
                _repository.Edit(destillery.Id, destillery.Name, destillery.FoundingYear, destillery.District);
                return RedirectToAction("Index");
            }
            else
                return View();
        }
    }
}

WebApp3/WhiskyDB.App/Controllers/WhiskyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WhiskyDB.Data.Repositories;
using WhiskyDB.Domain;
using WhiskyDB.App.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WhiskyDB.App.Controllers
{
    public class WhiskyController : Controller
    {
        private readonly IWhiskyRepository _whiskyRepository;
        private readonly IDestilleryRepository _destilleryRepository;
        private readonly ICaskRepository _caskRepository;

        public WhiskyController(IWhiskyRepository whiskyRepository, IDestilleryRepository destilleryRepository, ICaskRepository caskRepository)
        {
            _whiskyRepository = whiskyRepository;
            _destilleryRepository = destilleryRepository;
            _caskRepository = caskRepository;
        }

        public IActionResult Index()
        {
            return View(_whiskyRepository.GetAll());
        }

        public IActionResult Add()
        {
            ViewBag.Destilleries = _destilleryRepository.GetAll();
            ViewBag.Casks = _caskRepository.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddWhiskyViewModel model)
        {
            if (ModelState.IsValid)
            {
                Whisky whisky = model.Whisky;
                whisky.Destillery = _destilleryRepository.GetById(model.DestilleryId);
                List<Cask> casks = _caskRepository.GetAll().Where(c => model.CaskIds.Contains(c.Id)).ToList();
                _whiskyRepository.Add(model.Whisky, casks);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Destilleries = _destilleryRepository.GetAll();
                ViewBag.Casks = _caskRepository.GetAll();
                return View();
            }
        }

        public IActionResult Details(int id)
        {
            Whisky whisky = _whiskyRepository.GetById(id);
            IQueryable<Cask> casks = _caskRepository.GetByWhisky(whisky);
            return View(new WhiskyDetailsViewModel() { Whisky = whisky, Casks = casks });
        }

        public IActionResult Delete(int id)
        {
            Whisky whisky = _whiskyRepository.GetById(id);
            _whiskyRepository.Delete(whisky);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Whisky whisky = _whiskyRepository.GetById(id);
            List<int> caskIds = _caskRepository.GetByWhisky(whisky).Select(c => c.Id).ToList();
            ViewBag.Destilleries = _destilleryRepository.GetAll();
            ViewBag.Casks = _caskRepository.GetAll();
            return View(new AddWhiskyViewModel() { Whisky = whisky, DestilleryId = whisky.Destillery.Id, CaskIds = caskIds });
        }

        [HttpPost]
        public IActionResult Edit(AddWhiskyViewModel model)
        {
            if (ModelState.IsValid)
            {
                Whisky whisky = model.Whisky;
                whisky.Destillery = _destilleryRepository.GetById(model.DestilleryId);
                List<Cask> casks = _caskRepository.GetAll().Where(c => model.CaskIds.Contains(c.Id)).ToList();
                _whiskyRepository.Edit(model.Whisky.Id, model.Whisky.Name, model.Whisky.Age, model.Whisky.Description, model.Whisky.ImageUrl, model.Whisky.Destillery, casks);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Destilleries = _destilleryRepository.GetAll();
                ViewBag.Casks = _caskRepository.GetAll();
                return View(model);
            }
        }
    }
}

WebApp3/WhiskyDB.App/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiskyDB.App</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WhiskyDB.App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - WhiskyDB.App</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

WebApp3/WhiskyDB.App/Views/Shared/WhiskyBox.cshtml
@model WhiskyDB.Domain.Whisky

<div class="box col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img class="boxImage" src="@Model.ImageUrl" alt="">
        <div class="caption">
            <h3>
                <a class="btn btn-primary" asp-controller="Whisky" asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a>
            </h3>
        </div>
    </div>
</div>

WebApp3/WhiskyDB.App/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiskyDB.App</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Whisky" asp-action="Index">Whiskies</a></li>
                    <li><a asp-area="" asp-controller="Destillery" asp-action="Index">Destilleries</a></li>
                    <li><a asp-area="" asp-controller="Cask" asp-action="Index">Casks</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <p id="copy" >&copy; 2017 - WhiskyDB</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>